version: '3.7'
# This is application’s services configuration for development purposes only.

services:
  db:
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./.contrib/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  gulp:
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.gulp
    ports:
      - "35729:35729"
    volumes:
      - .:/app

  web:
    image: docker-registry.siecobywatelska.pl/feder/web
    build:
      context: .
      dockerfile: .contrib/docker/Dockerfile.web
      args:
        PYTHON_VERSION: '${PYTHON_VERSION:-3}'
        DJANGO_VERSION: '${DJANGO_VERSION:-==2.2.*}'
      cache_from:
        - docker-registry.siecobywatelska.pl/feder/web:latest
    volumes:
      - .:/code
    environment:
      DATABASE_URL: mysql://root:password@db/feder
    ports:
      - "8000:8000"