name: Python package

on: [push]

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python: 
          - 3.6
          - 3.7
        django:
          - "==2.2.*"
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: "true"
    - name: Start database early
      run: docker-compose up -d db
    - name: Build application
      run: make pull build
      env:
        PYTHON_VERSION: ${{ matrix.python }}
        DJANGO_VERSION: ${{ matrix.django }}
    - name: Lint check
      run: make lint
    - name: Migration check
      run: make check
    - name: Show MySQL logs
      if: failure()
      run: docker-compose logs db
    - name: Show settings
      run: make settings
    - name: Build test
      run: make test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application
      run: make build
      env:
        DJANGO_VERSION: "==2.2.*"
        PYTHON_VERSION: "3.7"
    - name: Build documentation
      run: make docs
